# Generated by Django 2.1.2 on 2018-10-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='income',
            field=models.FloatField(unique_for_date='start_date'),
        ),
    ]
