# Generated by Django 2.1.2 on 2018-10-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_auto_20181006_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
