# Generated by Django 2.2.14 on 2020-07-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0006_transaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_posted',
            field=models.DateTimeField(),
        ),
    ]
