# Generated by Django 2.2.14 on 2020-07-19 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0009_auto_20200719_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='payperiod',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.Transaction'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.Transaction'),
        ),
    ]
