# Generated by Django 2.2.14 on 2020-07-19 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0010_auto_20200719_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payperiod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.PayPeriod'),
        ),
    ]
