# Generated by Django 2.2.14 on 2020-07-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0011_auto_20200719_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payperiod',
            name='transaction',
        ),
        migrations.AddField(
            model_name='payperiod',
            name='transactions',
            field=models.ManyToManyField(null=True, to='cash.Transaction'),
        ),
    ]
