# Generated by Django 2.2.14 on 2020-07-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0012_auto_20200720_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='payperiod',
            name='budgeted_income',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payperiod',
            name='income',
            field=models.FloatField(),
        ),
    ]
