# Generated by Django 3.0.8 on 2020-07-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0013_auto_20200720_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='upload_parser',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
