# Generated by Django 3.0.8 on 2020-07-31 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0014_account_upload_parser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1000, null=True)),
                ('transaction_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='cash.Transaction')),
                ('transaction_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='cash.Transaction')),
            ],
        ),
    ]
