# Generated by Django 3.0.8 on 2020-07-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0016_auto_20200731_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='upload_parser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payperiod',
            name='transactions',
            field=models.ManyToManyField(to='cash.Transaction'),
        ),
    ]
