# Generated by Django 3.0.8 on 2020-08-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0018_auto_20200802_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payperiod',
            name='income',
        ),
    ]
