# Generated by Django 3.0.8 on 2020-08-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0019_remove_payperiod_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payperiod',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payperiod',
            name='start_date',
            field=models.DateField(unique=True),
        ),
    ]
