# Generated by Django 3.0.10 on 2020-10-09 20:16

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0020_auto_20200814_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='payperiod',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payperiod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.PayPeriod'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.Transaction'),
        ),
    ]
