# Generated by Django 3.0.10 on 2020-10-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0022_auto_20201010_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cash.Expense'),
        ),
    ]
