# Generated by Django 3.0.10 on 2020-10-10 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0023_auto_20201010_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='top_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cash.Expense'),
        ),
        migrations.AddField(
            model_name='payperiod',
            name='top_payperiod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cash.PayPeriod'),
        ),
    ]
