# Generated by Django 3.0.10 on 2020-10-10 21:03

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0024_auto_20201010_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgeted', models.FloatField()),
                ('budgeted_date', models.DateField(unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('recurrences', recurrence.fields.RecurrenceField(blank=True, null=True)),
                ('_carry_over', models.FloatField(blank=True, null=True)),
                ('first_occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cash.Income')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cash.Transaction')),
            ],
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payperiod',
        ),
        migrations.AlterField(
            model_name='expense',
            name='budgeted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PayPeriod',
        ),
        migrations.AddField(
            model_name='expense',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.Income'),
        ),
    ]
