# Generated by Django 3.0.10 on 2020-10-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0025_auto_20201010_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='budgeted_date',
            field=models.DateField(),
        ),
    ]
