# Generated by Django 3.0.10 on 2020-10-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0026_auto_20201010_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='top_expense',
            new_name='first_occurrence',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='expense',
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cash.Transaction'),
        ),
    ]
